---
abstract: 'Perl distribution for XInputSimulator'
author:
  - 'Ahmad Fatoum <athreef@cpan.org>'
build_requires:
  Alien::CMake: '0.07'
  IO::Socket::SSL: '0'
  Test::Alien: '0.05'
  Test::Alien::CPP: '0'
configure_requires:
  Alien::Base::ModuleBuild: '0.046'
  Alien::CMake: '0.07'
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-XInputSimulator
provides:
  Alien::XInputSimulator:
    file: lib/Alien/XInputSimulator.pm
    version: '0.001'
recommends:
  IO::Socket::SSL: '0'
requires:
  Alien::Base: '0.030'
  perl: '5.008'
resources:
  license: http://dev.perl.org/licenses/
version: '0.001'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
